version: "3"

volumes:
  chronograf:

services:
  influxdb:
    image: influxdb:1.7.9-alpine-custom
    build:
      context: "influxdb"
      args:
        - INFLUXDB_VERSION=1.7.9
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter
    volumes:
      - ${PWD}/volumes/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.7-alpine
    container_name: chronograf
    volumes:
      # create a named Docker volume:
      - chronograf:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.12.6-alpine-custom
    build:
      context: "telegraf"
      dockerfile: Dockerfile.x86_64
      args:
        - TELEGRAF_VERSION=1.12.6
    container_name: telegraf
    hostname: tgf-appserver01
    environment:
      - INFLUX_DB_HOST=http://influxdb:8086
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  jmeter-master:
    container_name: jmeter-master
    image: jmeter:5.2-alpine-generic
    hostname: controller-priv.2i.at
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    environment:
      DEBUG: 1
      JMETER_ROLE: MASTER
      JMETER_PLAN: /data/default_test_plan.jmx
      JMETER_REMOTE_SERVERS: -Rjmeter-slave:1099
      HEAP: -Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m
      # Set fixed RMI port & hostname!
      # see https://bz.apache.org/bugzilla/show_bug.cgi?id=62463
      #   and https://stackoverflow.com/questions/50752126/unable-to-start-jmeter-4-0-client-with-ssl-rmi/50888705
      #   for details on "client.rmi.localport=0"
      JMETER_OPTS: -Djava.net.preferIPv4Stack=true -Dclient.rmi.localport=0 -Djava.rmi.server.hostname=${HOST_PRIVATE_IP}
    # ports:
    #   - "40000:40000"
    volumes:
      - ${PWD}/volumes/jmeter:/data

  jmeter-slave:
    container_name: jmeter-slave
    image: jmeter:5.2-alpine-generic
    hostname: jmeter-slave1-priv.2i.at
    entrypoint: /jmeter/run
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    environment:
      JMETER_ROLE: SLAVE
      HEAP: -Xms512m -Xmx512g -XX:MaxMetaspaceSize=256m
      # Set fixed RMI port & hostname!
      SERVER_PORT: 1099
      JMETER_OPTS: -Djava.net.preferIPv4Stack=true -Dserver.rmi.localport=50000 -Djava.rmi.server.hostname=${HOST_PRIVATE_IP}
    ports:
      # bind to private IPs only instead of *
      # - "192.168.99.100:50000:50000"
      # - "192.168.99.100:1099:1099"
      - "${HOST_PRIVATE_IP}:50000:50000"
      - "${HOST_PRIVATE_IP}:1099:1099"
    volumes:
      - ${PWD}/volumes/jmeter:/data

  grafana:
    container_name: grafana
    build:
      context: "grafana"
    volumes:
      - ${PWD}/volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
