version: '3'

services:
        influxdb:
                image: influxdb:1.7-alpine
                environment:
                        - INFLUXDB_DB=jmeter
        jmeter:
                build:
                        context: "jmeter"
                        args:
                                - JMETER_VERSION=5.2
                environment:
                        JMETER_TEST: default_test_plan.jmx
                        HEAP: -Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m
                depends_on:
                        - influxdb
        grafana:
                build:
                        context: "grafana"
                ports:
                        - "3000:3000"
                depends_on:
                        - influxdb
                        - jmeter
