version: "3"

services:
  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter
    volumes:
      - ${PWD}/volumes/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.7-alpine
    container_name: chronograf
    volumes:
      # Mount for chronograf database
      - ${PWD}/chronograf:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.12-alpine
    container_name: telegraf
    hostname: tgf-appserver01
    environment:
      - INFLUX_DB_HOST=http://influxdb:8086
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  jmeter:
    container_name: jmeter
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    volumes:
      - ${PWD}/volumes/jmeter:/data
    environment:
      JMETER_PLAN: default_test_plan.jmx
      HEAP: -Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m
    depends_on:
      - influxdb

  grafana:
    container_name: grafana
    build:
      context: "grafana"
    volumes:
      - ${PWD}/volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  chronograf:
