version: "3"

volumes:
  chronograf:

services:
  influxdb:
    image: influxdb:1.7.9-alpine-custom
    build:
      context: "influxdb"
      args:
        - INFLUXDB_VERSION=1.7.9
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter
    volumes:
      - ${PWD}/volumes/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.7-alpine
    container_name: chronograf
    volumes:
      # create a named Docker volume:
      - chronograf:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.12.6-alpine-custom
    build:
      context: "telegraf"
      args:
        - TELEGRAF_VERSION=1.12.6
    container_name: telegraf
    hostname: tgf-appserver01
    environment:
      - INFLUX_DB_HOST=http://influxdb:8086
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - ${PWD}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  jmeter-master:
    container_name: jmeter-master
    image: jmeter:5.2-alpine-generic
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    environment:
      JMETER_ROLE: MASTER
      JMETER_PLAN: /data/default_test_plan.jmx
      JMETER_REMOTE_SERVERS: -R172.27.0.3:51099
      HEAP: -Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m
      JMETER_OPTS: -Dclient.rmi.localport=40000
    ports:
      - "40000:40000"
    volumes:
      - ${PWD}/volumes/jmeter:/data
    # depends_on:
    #   - influxdb

  jmeter-slave:
    container_name: jmeter-slave
    image: jmeter:5.2-alpine-generic
    entrypoint: /jmeter/run
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    environment:
      JMETER_ROLE: SLAVE
      HEAP: -Xms64m -Xmx512m -XX:MaxMetaspaceSize=256m
      # Fixed RMI server port
      RMI_HOST_DEF: -Dserver.rmi.localport=51000
      # Fixed RMI registry port
      SERVER_PORT: 51099
    ports:
      - "51000:51000"
      - "51099:51099"
    volumes:
      - ${PWD}/volumes/jmeter:/data

  grafana:
    container_name: grafana
    build:
      context: "grafana"
    volumes:
      - ${PWD}/volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
