version: "3"

volumes:
  chronograf:

services:
  jmeter-slave:
    container_name: jmeter-slave
    image: jmeter:5.2-alpine-generic
    hostname: jmeter-slave1-priv.2i.at
    entrypoint: /jmeter/run
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    environment:
      JMETER_ROLE: SLAVE
      HEAP: -Xms512m -Xmx512g -XX:MaxMetaspaceSize=256m
      # Set fixed RMI port & hostname!
      SERVER_PORT: 1099
      JMETER_OPTS: -Djava.net.preferIPv4Stack=true -Dserver.rmi.localport=50000 -Djava.rmi.server.hostname=${RMI_HOST}
    ports:
      # bind to private IPs only instead of *
      - "${HOST_PRIVATE_IP}:50000:50000"
      - "${HOST_PRIVATE_IP}:1099:1099"
    volumes:
      - ${PWD}/volumes/jmeter:/data
