version: "3"

services:
  influxdb:
    image: influxdb:1.7-alpine
    # ports:
    #    - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter
    volumes:
      - ${PWD}/volumes/influxdb:/var/lib/influxdb

  jmeter:
    build:
      context: "jmeter"
      args:
        - JMETER_VERSION=5.2
    volumes:
      - ${PWD}/volumes/jmeter:/data
    environment:
      JMETER_PLAN: default_test_plan.jmx
      HEAP: -Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m
    depends_on:
      - influxdb

  grafana:
    build:
      context: "grafana"
    volumes:
      - ${PWD}/volumes/grafana:/var/lib/grafana
    ports:
      - "40386:3000"
    depends_on:
      - influxdb
